exp_name: usat_meter_ft_naip
version: 0
task: MultiLabelClassification
random_seed: 42

training_method: finetuning
feature_opt: cls_token

training:
  batch_size: 1
  # train loader
  train_loader_worker: 8
  eval_loader_worker: 8
  #optimizer
  optimizer: "AdamW"
  optimizer_cfg:
    lr: 1.0e-5
    weight_decay: 0.1
  scheduler: "Cosine"
  warm_up_epoch: 1
  trainer:
    # GPU config
    gpus: 10
    strategy: ddp
    unused_params: False
    # Logging config
    save_dir: /deep2/group/aicc-bootcamp/self-sup/results/downstream
    # Callbacks
    save_top_k: 5 # checkpointing
    monitor_metric: Val/epoch_avg_mAP
    monitor_mode: max
    patience: 5 # early stop
    # Misc
    gradient_clip_val: 0.5
    limit_train_batches: 1.0
    enable_model_summary: False
    max_epochs: 5

dataset:
  name: MeterMLDataset
  train_args:
    base_path: /scr/meter
    split: 'train'
    standardize: True
    ground_cover: 640
    data_percent: 1.0
    products: ["naip"]
  eval_args:
    base_path: /scr/meter
    split: 'val'
    standardize: True
    ground_cover: 640
    data_percent: 1.0
    products: ["naip"]
  test_args:
    base_path: /scr/meter
    split: 'test'
    standardize: True
    ground_cover: 640
    data_percent: 1.0
    products: ["naip"]

models:
  encoder:
    type: usat_vit_large_encoder_no_prod_embed
    ckpt: /deep2/group/aicc-bootcamp/self-sup/results/pretraining/PT_SatlasFull_yes_super_yes_group_no_sensor_USatMAE_group/version_0/ckpt/epoch=24-step=564875.ckpt
    strict: False
    target_model: mae
    args:
      input_parmas:
        ground_cover: 1280
        groups: [['NAIP:Red', 'NAIP:Blue', 'NAIP:Green', 'NAIP:NIR']]
        NAIP:Red: {'GSD': 1, 'num_patch': 80}
        NAIP:Green: {'GSD': 1, 'num_patch': 80}
        NAIP:Blue: {'GSD': 1, 'num_patch': 80}
        NAIP:NIR: {'GSD': 1, 'num_patch': 80}
        use_superposition_encoding: True
      encode_type: concat
    
  head:
    type: ClassifierHead
    args:
      input_size: 1024
      num_classes: 6